In [1]:
import torch
tns = torch.randn(9, 12)
tns1 = tns[0:5, 0:4]
tns2 = tns[5:, 4:]

resultado = torch.mm(tns1, tns2)
print(resultado.size())

torch.Size([5, 8])


In [2]:
import torch
lista = [ [1,2,3],
          [4,5,6] ]

tns = torch.Tensor(lista)
print(tns.dtype)
print(tns)

print('')
tns = torch.DoubleTensor(lista)
print(tns.dtype)
print(tns)

print('')
tns = torch.LongTensor(lista)
print(tns.dtype)
print(tns)

torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])

torch.float64
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

torch.int64
tensor([[1, 2, 3],
        [4, 5, 6]])


In [3]:
import numpy as np

arr = np.random.rand(3,4)
arr = arr.astype(int)
print(arr)
print(arr.dtype)

print('')
tns = torch.from_numpy(arr)
print(tns)
print(tns.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int64

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])
torch.int64


In [4]:
tns1 = torch.ones(2, 3)
tns0 = torch.zeros(3, 5)
tnsr = torch.randn(3, 3)

print(tns1)
print(tns0)
print(tnsr)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[ 0.2471, -0.0016, -0.9000],
        [ 0.3998, -1.0926,  0.2138],
        [-0.0256, -0.9676, -1.2655]])


In [5]:
arr = tnsr.data.numpy()
print(arr)

[[ 0.2471019  -0.00158808 -0.90000576]
 [ 0.3997825  -1.0925585   0.21382762]
 [-0.02555681 -0.9676367  -1.2655214 ]]


In [6]:
print(tnsr[0:2, 2].data.numpy())
print(tnsr[0, 1].item())

[-0.90000576  0.21382762]
-0.001588077750056982


In [7]:
tns1 = torch.randn(2,2,3)
tns2 = torch.ones(2,2,3)

print(tns1)
print(tns2)

print('')

print(tns1*tns2)

tensor([[[ 0.3450,  1.9265,  1.1230],
         [-0.5158, -0.1831, -1.3778]],

        [[-0.5042, -0.2511,  0.3277],
         [ 1.2107,  0.1587,  0.1599]]])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

tensor([[[ 0.3450,  1.9265,  1.1230],
         [-0.5158, -0.1831, -1.3778]],

        [[-0.5042, -0.2511,  0.3277],
         [ 1.2107,  0.1587,  0.1599]]])


In [8]:
print(tns2.size())

print(tns2.view(tns2.size(0), -1))

torch.Size([2, 2, 3])
tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])


In [9]:
if torch.cuda.is_available():
  device = torch.device('cuda')
else:
  device = torch.device('cpu')

print(device)
tns2 = tns2.to(device)
print(tns2)

cpu
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
