In [1]:
import torch
from torch import nn

In [2]:
torch.manual_seed(42)

perceptron = nn.Linear(3, 1)
print(perceptron)

Linear(in_features=3, out_features=1, bias=True)


In [3]:
for nome, tensor in perceptron.named_parameters():
  print(nome, tensor.data)

print('')
print(perceptron.weight.data)
print(perceptron.bias.data)

weight tensor([[ 0.4414,  0.4792, -0.1353]])
bias tensor([0.5304])

tensor([[ 0.4414,  0.4792, -0.1353]])
tensor([0.5304])


In [4]:
w1, w2, w3 = perceptron.weight.data.numpy()[0]
b = perceptron.bias.data.numpy()

In [5]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

def plot3d(perceptron):

  w1, w2, w3 = perceptron.weight.data.numpy()[0]
  b = perceptron.bias.data.numpy()

  X1 = np.linspace(-1,1,10)
  X2 = np.linspace(-1,1,10)

  X1, X2 = np.meshgrid(X1,X2)

  X3 = (b - w1*X1 - w2*X2) / w3

  fig = plt.figure(figsize=(10, 8))

  ax = fig.gca(projection='3d')
  ax.view_init(azim=180)

  ax.plot_surface(X1, X2, X3, cmap='plasma')

In [6]:
plot3d(perceptron)

TypeError: FigureBase.gca() got an unexpected keyword argument 'projection'

<Figure size 1000x800 with 0 Axes>

In [7]:
X = torch.Tensor([0, 1, 2])
y = perceptron(X)

print(y)

plot3d(perceptron)
plt.plot([X[0]], [X[1]], [X[2]], color='r', marker='^', markersize=20)

tensor([0.7391], grad_fn=<ViewBackward0>)


TypeError: FigureBase.gca() got an unexpected keyword argument 'projection'

<Figure size 1000x800 with 0 Axes>